config/routes.rb
Rails.application.routes.draw do


  get "reports/renewal_report"
  get "reports/dynamic_renewal_data"

  get "agreement_renewals/form"
  post "agreement_renewals/form"

  get "users/franchisee_profile"

  get "due_payslip" => "installment_details#due_royalty_pay_slip"
  post "installment_details/update_franchisee_due_royalty_payment"
  get "due_paydetail" => "installment_details#due_royalty_payment_detail"

  get "installment_details/due_royalty_amount"
  
  post "franchisees/emailcheck"

  get "students/deactivate_student"
  get "students/activate_student"

  get "students/deactivated_student_list"

  get "student_fee_pays/fees_receipt"

  get "franchisee_payslip" => "royalty_details#franchisee_royalty_pay_slip"
  post "royalty_details/update_franchisee_royalty_payment"
  get "franchisee_paydetail" => "royalty_details#franchisee_royalty_payment_detail"

  get "company_payslip" => "company_royalty_details#company_royalty_pay_slip"
  post "company_royalty_details/update_company_royalty_payment"
  get "company_paydetail" => "company_royalty_details#company_royalty_payment_detail"

  post "installment_details/installment_pay"

  get "installment_details/franchisee_payment_detail"

  get "installment_details/franchisee_pay_slip"
  post "installment_details/franchisee_pay_slip"

  get "royalty_details/royalty"
  get "royalty_details/company"
  get "royalty_details/franchisee_royalty"
  get "royalty_details/current_month_royalty"
  get "royalty_details/get_month_year_franchisee_child_royalty"
  get "royalty_details/current_month_company_royalty"
  get "royalty_details/get_month_year_company_royalty"
  get "pay_status" => "royalty_details#pay_status"
  get "our_pay_status" => "royalty_details#our_pay_status"
  get "our_company_pay" => "royalty_details#our_company_pay"
  get "royalty_pay_to_company" => "royalty_details#royalty_pay_to_company"
  get "royalty_details/pay_status_updation"
  get "announcements/announcement_deactive"

  get 'royalty_details/change_status_true'
  get 'royalty_details/change_status_false'

  get "order_requests/invoice_detail"

  get "invoices/invoice_payment_detail"

  get "invoices/invoice_pay_slip"
  post "invoices/invoice_pay_slip"

  get "purchases/item_check"

  get "purchases/payment_detail"

  get "purchases/pay_slip"
  post "purchases/pay_slip"

  #get "purchases/amount_calculation"

  get "employee_attendances/get_month_year_leave"

  get "emp_monthly_salaries/get_month_year_salary"
  post "emp_monthly_salaries/get_month_year_salary"
    
  get "employee_attendances/monthly_leave"

  get "employee_attendances/leave"
  post "employee_attendances/leave"

  get "print_franchisee" => "franchisees#print_franchisee"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#validate_logins'
  get 'logout' => 'sessions#destroy'
  
  get "franchisees/franchisee_agreement"
  post "franchisees/franchisee_agreement"

  get "franchisees/get_type"
  post "franchisees/get_type"

  get "franchisees/dashboard"
  
  get "sessions/forgot_password"
  post "sessions/forgot_password"
  
  get "sessions/forgot_password_link"
  post "sessions/forgot_password_link"

  get  "reset_password" => "sessions#reset_password", :as => "reset_password"
  post "sessions/reset_password"
  
  post "users/update_new_password"

  
  get "franchisees/franchisee_level"
  
  get "student_attendance"=>"students#student_attendance"
  post "student_attendance"=>"students#student_attendance_create"
  get "attendance_destroy"=>"students#attendance_destroy"
  get "franchisee_dashboard" => "franchisees#franchisee_dashboard"

  get "student_reports" => "reports#student_reports"
  get "student_report_show" => "reports#student_report_show"
  get "student_report_generates" => "reports#student_report_generates"

  get "upgrade_level" => "students#level_show"
  get "student_detail_show" => "students#student_details_show"

  get "student_level_update" => "students#student_level_update"

  get "franchisee_tree" => "franchisees#franchisee_tree"

  get "students_report"=> "reports#all_student_report"

  get "reports/monthwise_student_report"
  get "reports/report_xls_generate"
  get "reports/income"
  get "reports/dynamic_income"



  get "expense_category"=>"expenses#expense_category"
  post "expense_category"=>"expenses#expense_category_create"

  
  resources :agreement_renewals
  resources :expenses

  resources :vendors
  
  resources :announcement_fors
  resources :announcements

  resources :company_royalty_details
  resources :royalty_details
  resources :student_fee_pays
  
  resources :student_fee_pays
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests

  resources :franchisee_inventory_stocks
  resources :installment_details

  resources :franchisee_inventory_stocks
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests
  resources :payments
  resources :purchase_items
  resources :purchases
  resources :company_inventory_stocks

  resources :emp_monthly_salaries
  resources :student_details
  resources :students
  resources :franchisee_agreements
  resources :franchisee_contacts
  resources :franchisee_personals
  resources :franchisees
  resources :users
  resources :employee_attendances
  resources :inventory_items
  resources :employee_contacts
  resources :employee_personals
  resources :employee_salaries
  resources :employees
  resources :roles
  resources :batches

  root "franchisees#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   mount SubdivisionSelect::Engine, at: 'subdivisions'
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_one :employee_salary, :dependent => :destroy
	has_one :employee_personal, :dependent => :destroy
	has_one :employee_contact, :dependent => :destroy
	has_many :employee_attendances, :dependent => :destroy
	has_many :emp_monthly_salaries, :dependent => :destroy
	belongs_to :profile_image, optional: true
	mount_uploader :resume, ResumeUploader

	accepts_nested_attributes_for :employee_salary, allow_destroy: true
	accepts_nested_attributes_for :employee_personal, allow_destroy: true
	accepts_nested_attributes_for :employee_contact, allow_destroy: true
	accepts_nested_attributes_for :profile_image, allow_destroy: true

	validates_presence_of :employee_identity, :prefix, :first_name, :last_name, :date_of_joining, :message => "Required"
	validates_format_of :email_id, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, :allow_blank => true, :message=> "Invalid"
	validates_uniqueness_of :employee_identity
	validates_uniqueness_of :email_id

	def self.create_salary_entry(emp_id, date_of_joining, salary_amount)
		
		leave_count = (Date.today.beginning_of_month...date_of_joining.to_date).count

		salary_per_day = (salary_amount.to_f / ((Date.today.beginning_of_month..Date.today.end_of_month).count))
		 
		salary_payable = salary_amount.to_f - (salary_per_day * leave_count) 
		#if date_of_joining.to_date.month == Date.current.month && date_of_joining.to_date.year == Date.current.year
  			EmpMonthlySalary.create(employee_id: emp_id, salary_for: date_of_joining.to_date, no_of_leave: leave_count, net_salary: salary_payable.round)
  	end

  	def self.create_leave_entry(emp_id, date_of_joining)
  		@leave_dates = (date_of_joining.to_date.beginning_of_month)..(date_of_joining.to_date-1)
  		@leave_dates.map do |date_of_leave|
  			EmployeeAttendance.create(employee_id: emp_id, leave_date: date_of_leave, reason: "Joined in the middle", apply_date: date_of_joining)
  		end
  	end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

 
  def index
    @employees = Employee.all
  end

  
  def show
  end

  
  def new
    @employee = Employee.new
    @employee.build_employee_salary
    @employee.build_employee_personal
    @employee.build_employee_contact
    @employee.build_profile_image
  end

  
  def edit 
    @employee.build_profile_image
  end

  
  def create
    date_of_joining = params[:employee][:date_of_joining]
    salary_amount = params[:employee][:employee_salary_attributes][:salary_amount]
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        Employee.create_leave_entry(@employee.id, date_of_joining)
        Employee.create_salary_entry(@employee.id, date_of_joining, salary_amount)
        format.html { redirect_to employees_url, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    
    def set_employee
      @employee = Employee.find(params[:id])
    end

    
    def employee_params
      params.require(:employee).permit!#(:employee_identity, :prefix, :first_name, :last_name, :email_id, :department, :job_title, :date_of_joining)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def salutations
		["Mr.", "Mrs.", "Ms.", "Dr."]
	end
end

app/views/employees/edit.html.erb
<div class="card">
	<div class="card-header">
		<h3>Editing Employee
		<%= link_to "<i class='fa fa-reply'></i>".html_safe, employees_path, class: " head-title pull-right", data: { confirm: 'Do you want to go to previous page?' } %></h3>
	</div>
	<div class="card-body"><%= render 'form', employee: @employee %></div>
</div>
<style type="text/css">
.btn-orange{
background-color: #E26616;
color: #fff;
}
</style>

app/views/employees/index.html.erb
    <!-- employee cards  -->
<div class="card">
  <div class="card-header">
    <h3>Employees
      <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_employee_path, class: " head-title pull-right" %>
    </h3>
  </div>

  <div class="card-body">
<div class="container">
  <div class="row">

   <% @employees.each do |employee| %>
    <div class="col-lg-4 col-sm-6">
      <div class="card hovercard">
        <div class="row empl-detail">
          <div class="avatar">
            <% if employee.profile_image.present? %>
                <%= image_tag employee.profile_image.image_url %>
            <% elsif employee.employee_personal.gender == "Male" %>
                <img alt="img" src="<%= asset_url("professional_men.png") %>">
            <% elsif employee.employee_personal.gender == "Female"%>
                <img alt="img" src="<%= asset_url("professional_women.jpeg") %>">
            <% else %>
                <img alt="img" src="<%= asset_url("unknown.png") %>">
            <% end %>
          </div>
          <div class="info">
            <div class="title">
              <p><%= employee.prefix %> <%= employee.first_name %> <%= employee.last_name %></p>
              <p class="phno"><%= employee.employee_contact.contact_no if employee.employee_contact %></p>
            </div>
            <div class="desc"><%= employee.employee_identity %></div>
            <div class="desc">Leave for <%= Date.today.strftime("%B")%> : <span><%= employee.employee_attendances.where(:leave_date => Date.current.beginning_of_month..Date.current.end_of_month).count %></span></div>
          </div>  

        <div class="po-markup">  
                <a class="detail-btn float-right po-link" href="#"  data-trigger="focus"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a> 
            <div class="po-content hidden">
                <div class="po-body">   
                  <ul>
                  <li><%= link_to "<i class='btn btn-sm btn-orange fa fa-eye'></i>".html_safe, employee, title: "View" %></li>
                  <li><%= link_to "<i class='btn btn-sm btn-orange fa fa-pencil'></i>".html_safe, edit_employee_path(employee), title: "Edit" %></li>
                  <li><%= link_to "<i class='btn btn-sm btn-orange fa fa-plus'></i>".html_safe, employee_attendances_url(id: employee.id), title: "Add leave" %></li>
                   </ul>
                </div>
            </div>  
        </div>

        </div>
      </div>
    </div>  
  <% end %>   

  </div>
</div>

</div>
</div>


<style type="text/css">

  .card.hovercard{

    margin: 10px 0 10px 0;

    background-color: #efefef;

    border-top-width: 0;

    border-bottom-width: 2px;

    -webkit-border-radius: 3px;

    -moz-border-radius: 3px;

    border-radius: 3px;

    -webkit-box-shadow: none;

    -moz-box-shadow: none;

    box-shadow: none;

    -webkit-box-sizing: border-box;

    -moz-box-sizing: border-box;

    box-sizing: border-box;


    height: 116px;

}

.card .card-heading {

    padding: 0 20px;

    margin: 0;

}

.card .card-heading.simple {

    font-size: 20px;

    font-weight: 300;

    color: #777;

    border-bottom: 1px solid #e5e5e5;

}

.card .card-heading.image img {

    display: inline-block;

    width: 46px;

    height: 46px;

    margin-right: 15px;

    vertical-align: top;

    border: 0;

    -webkit-border-radius: 50%;

    -moz-border-radius: 50%;

    border-radius: 50%;

}

.card .card-heading.image .card-heading-header {

    display: inline-block;

    vertical-align: top;

}

.card .card-heading.image .card-heading-header h3 {

    margin: 0;

    font-size: 14px;

    line-height: 16px;

    color: #262626;

}

.card .card-heading.image .card-heading-header span {

    font-size: 12px;

    color: #999999;

}

.card .card-body {

    padding: 0 20px;

    margin-top: 20px;

}

.card .card-media {

    padding: 0 20px;

    margin: 0 -14px;

}

.card .card-media img {

    max-width: 100%;

    max-height: 100%;

}

.card .card-actions {

    min-height: 30px;

    padding: 0 20px 20px 20px;

    margin: 20px 0 0 0;

}

.card .card-comments {

    padding: 20px;

    margin: 0;

    background-color: #f8f8f8;

}

.card .card-comments .comments-collapse-toggle {

    padding: 0;

    margin: 0 20px 12px 20px;

}

.card .card-comments .comments-collapse-toggle a,

.card .card-comments .comments-collapse-toggle span {

    padding-right: 5px;

    overflow: hidden;

    font-size: 12px;

    color: #999;

    text-overflow: ellipsis;

    white-space: nowrap;

}

.card-comments .media-heading {

    font-size: 13px;

    font-weight: bold;

}

.card.people {

    position: relative;

    display: inline-block;

    width: 170px;

    height: 300px;

    padding-top: 0;

    margin-left: 20px;

    overflow: hidden;

    vertical-align: top;

}

.card.people:first-child {

    margin-left: 0;

}

.card.people .card-top {

    position: absolute;

    top: 0;

    left: 0;

    display: inline-block;

    width: 170px;

    height: 150px;

    background-color: #ffffff;

}

.card.people .card-top.green {

    background-color: #53a93f;

}

.card.people .card-top.blue {

    background-color: #427fed;

}

.card.people .card-info {

    position: absolute;

    top: 150px;

    display: inline-block;

    width: 100%;

    height: 101px;

    overflow: hidden;

    background: #ffffff;

    -webkit-box-sizing: border-box;

    -moz-box-sizing: border-box;

    box-sizing: border-box;

}

.card.people .card-info .title {

    display: block;

    margin: 8px 14px 0 14px;

    overflow: hidden;

    font-size: 16px;

    font-weight: bold;

    line-height: 18px;

    color: #404040;

}

.card.people .card-info .desc {

    display: block;

    margin: 8px 14px 0 14px;

    overflow: hidden;

    font-size: 12px;

    line-height: 16px;

    color: #0c0c0c;

    text-overflow: ellipsis;

}
.card.hovercard .avatar img {

   width: 60px;

    height: 67px;

    max-width: 100px;

    max-height: 100px;

    -webkit-border-radius: 25%;

    -moz-border-radius: 50%;

    border-radius: 30%;

    border: 5px solid rgba(255,255,255,0.5);

    overflow: hidden;

}

.card.hovercard .info {

   padding: 5px;

}

.card.hovercard .info .title {

    margin-bottom: 4px;

    font-size: 24px;

    line-height: 1;

    color: #262626;

    vertical-align: middle;

}

.card.hovercard .info .desc {

    overflow: hidden;

    font-size: 12px;

    line-height: 20px;

    color: #3a3a3a;

    text-overflow: ellipsis;

}

.empl-detail{

  margin:0px;

}

.avatar{

  margin: 5px;

}

.card.hovercard .info .title p{

  margin-bottom: 0px !important;

    font-size: 11px;

    color: #e36612  ;

    font-weight: 600;

    width: 183px;

}

.detail-btn{

  position: absolute;

    right: 10px;

    top: 5px;

}

.detail-btn .fa-ellipsis-v{

    font-size: 22px;

    color: #e36612;

    padding: 5px 5px;

}

.card.hovercard .info .title .phno{

  font-size: 13px;

font-weight: 500;

}

.po-content{

  display: none;

}

.popover-body ul{

  list-style:none !important;

  padding-left:0px;

}

.popover-body ul li{

  padding-top: 10px;

}

/*.popover-body ul li .btn{

  width: 25px;

}
*/
.popover-body ul li .btn:hover{

 background-color: #de681d;

border-color: #de681d;

}


</style>

<script>

$(document).ready(function(){

    $('[data-toggle="popover"]').popover(); 


});

$(document).ready(function() {

            $('.po-markup > .po-link').popover({

            trigger: 'active',

            html: true,  // must have if HTML is contained in popover

            // get the title and conent

            title: function() {

                return $(this).parent().find('.po-title').html();

            },

            content: function() {

                return $(this).parent().find('.po-body').html();

            },

            container: 'body',

            placement: 'left'

            });

        }); 

</script>

app/views/employees/new.html.erb
<!-- <div class="card">
	<div class="card-header">
		<h3>New Employee
		<%#= link_to "<i class='fa fa-reply'></i>".html_safe, employees_path, class: "pull-right head-title", data: { confirm: 'Do you want to go to previous page?' } %></h3>
	</div>
	<div class="card-body"><%#= render 'form', employee: @employee %></div>
</div>
<style type="text/css">
.btn-orange{
background-color: #E26616;
color: #fff;
}
</style> -->


<div class="card multi-step-form">
	<div class="card-header">
		<h3>New Employee
		<%= link_to "<i class='fa fa-reply'></i>".html_safe, employees_path, class: "pull-right head-title", data: { confirm: 'Do you want to go to previous page?' } %></h3>
	</div>
		<div class="card-body">

        <%= render 'form', employee: @employee %>


      <!-- Circles which indicates the steps of the form: -->
 <!--  <div id="progressbar" style="text-align:center;margin-bottom:40px;">
    <span class="step">Franchisee</span>
    <span class="step">Onwer</span>
    <span class="step">Agreement</span>
    <span class="step">File upoload</span>
  </div> -->


	</div>
</div>

app/views/employees/show.html.erb
<section class="show-profile">
<div class="card">
<div class="col-md-12 pt-3">
<h4 class="pb-0"> Employee Details
<%= link_to "<i class='btn btn-info btn-sm'> Back</i>".html_safe, employees_path, class: "pull-right" %>
<hr style="border-color: #E26616;">
</h4>
</div>
<div class="row profile">
<div class="col-md-6">
<div class="media">
  <div class="media-body">
  <div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Employee Id<span>:</span></label>
  <div class="col-md-8">
    <p class="reg-date"><span><%= @employee.employee_identity %></span></p>
    <!-- .to_date.strftime("%d-%m-%Y") -->
  </div>
</div>

<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Full Name<span>:</span></label>
  <div class="col-md-8">
  <p class="dob"><span> <%= @employee.prefix %> <%= @employee.first_name %> </span></p>
  </div>
</div>

<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Email Id<span>:</span></label>
  <div class="col-md-8">
 <p class="age"><span> <%= @employee.email_id %></span></p>
  </div>
</div>
 </div>
 </div>
</div>

<div class="col-md-6">
<form class="address-info">
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Department<span>:</span></label>
  <div class="col-md-8">
    <p class="con-no"><span> <%= @employee.department %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Job Title<span>:</span></label>
  <div class="col-md-8">
    <p class="address"><span> <%= @employee.job_title %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Date of Joining<span>:</span></label>
  <div class="col-md-8">
    <p class="address"><span><%= @employee.date_of_joining.present? ? @employee.date_of_joining.to_date.strftime("%d-%m-%Y") : nil  %></span></p>
  </div>
</div>
</form>
</div>
</div>
</div>


<div class="card">
<div class="row profile">

<div class="col-md-6">
<h4 >Salary Details</h4>
<hr style="border-color: #E26616;">
<div class="Acadamic-prof ml-3">
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Salary<span>:</span></label>
  <div class="col-md-8">
    <p class="level"><span><%= @employee.employee_salary.salary_amount %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Account Holder Name<span>:</span></label>
  <div class="col-md-8">
    <p class="class"><span><%= @employee.employee_salary.account_holder_name %></span></p>
  </div>
</div>


<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Account Number<span>:</span></label>
  <div class="col-md-8">
    <p class="batch"><span><%= @employee.employee_salary.account_number %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">IFSC Code<span>:</span></label>
  <div class="col-md-8">
    <p class="batch"><span><%= @employee.employee_salary.ifsc_code %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Bank Name<span>:</span></label>
  <div class="col-md-8">
    <p class="batch"><span><%= @employee.employee_salary.bank_name %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Account Type<span>:</span></label>
  <div class="col-md-8">
    <p class="sch-name"><span> <%= @employee.employee_salary.account_type %></span></p>
  </div>
</div>
</div>
</div>

<div class="col-md-6">
<h4>Personal Details</h4>
<hr style="border-color: #E26616;">
<div class="Acadamic-prof row">
<div class="col-12">
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Gender<span>:</span></label>
  <div class="col-md-8">
    <p class="Father-name"><span><%= @employee.employee_personal.gender %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Marital Status<span>:</span></label>
  <div class="col-md-8">
    <p class="f-mail-id"><span><%= @employee.employee_personal.marrital_status == true ? "Married" : "Unmarried" %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Nationality<span>:</span></label>
  <div class="col-md-8">
    <p class="ocptn"><span><%= @employee.employee_personal.nationality %></span></p>
  </div>
</div>
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Date of Birth<span>:</span></label>
  <div class="col-md-8">
    <p class="f-con-no"><span><%= @employee.employee_personal.date_of_birth.present? ? @employee.employee_personal.date_of_birth.to_date.strftime("%d-%m-%Y") : nil %></span></p>
  </div>
</div>
</div>
<div class="col-12">
<div class="form-group row">
  <label for="example-text-input" class="col-md-4 col-form-label">Blood Group<span>:</span></label>
  <div class="col-md-8">
    <p class="Mother-name"><span><%= @employee.employee_personal.blood_group %></span></p>
  </div>
</div>

</div>

</div>
</div>

</div>
</div>


<div class="card">
<div class="row profile">
<div class="col-md-12">
<h4>Contact Details</h4>
<hr style="border-color: #E26616;">
</div>
 <div class="row col-md-12 reference">
  <div class="col-md-6">
  <div class="form-group">
  <label for="example-text-input" class="col-md-12 col-form-label">Contact Number</label>
  <div class="col-md-12">
    <p><%= @employee.employee_contact.contact_no %></p>
  </div>
</div>
  </div>

  <div class="col-md-6">
  <div class="form-group">
  <label for="example-text-input" class="col-md-12 col-form-label">Address</label>
  <div class="col-md-12">
    <p><%= @employee.employee_contact.address %></p>
  </div>
</div>
  </div>
  </div>

  <div class="row col-md-12 reference">
  <div class="col-md-6">
  <div class="form-group">
  <label for="example-text-input" class="col-md-12 col-form-label">Country</label>
  <div class="col-md-12">
    <p><%= @employee.employee_contact.country %></p>
  </div>
</div>
  </div>

  <div class="col-md-6">
  <div class="form-group">
  <label for="example-text-input" class="col-md-12 col-form-label">State</label>
  <div class="col-md-12">
    <p><%= @employee.employee_contact.state %></p>
  </div>
</div>
  </div>
  </div>

  <div class="row col-md-12 reference">
  <div class="col-md-6">
  <div class="form-group">
  <label for="example-text-input" class="col-md-12 col-form-label">City</label>
  <div class="col-md-12">
    <p><%= @employee.employee_contact.city %></p>
  </div>
</div>
  </div>

  <div class="col-md-6">
  <div class="form-group">
  <label for="example-text-input" class="col-md-12 col-form-label">Pincode</label>
  <div class="col-md-12">
    <p><%= @employee.employee_contact.pincode %></p>
  </div>
</div>
  </div>
  </div>

</div>
</div>  

  <div class="pl-4 row">
      <div class="col-md">
          <div class="form-group row">
              <div class="col-md-3">
                  <label for="example-text-input" class="col-form-label">
                    Profile Picture</label>
              </div>
              <div class="col-md-3">
                  <% if @employee.profile_image.present? %>
                      <p class="reg-date"><span><strong style="color: #000;">:</strong> <%=image_tag @employee.profile_image.image_url, :style=>"width:150px; height:150px"%></span></p>
                  <%else%>
                      <p class="reg-date"><span style="width:150px; height:150px;"><strong style="color: #000;">:</strong>No Profile Picture</span></p>
                  <%end%>
              </div>              
          </div>
      </div>
</div>
<br>
  <div class="pl-4 row">
      <div class="col-md">
          <div class="form-group row">
              <div class="col-md-3">
                  <label for="example-text-input" class="col-form-label">
                    Resume</label>
              </div>
              <div class="col-md-3">
                  <% if @employee.resume.present? %>
                      <iframe src="<%= @employee.resume %>"></iframe>
                      <!-- <p class="reg-date"><span><strong style="color: #000;">:</strong> <%#=image_tag @employee.resume, :style=>"width:150px; height:150px"%></span></p> -->
                  <%else%>
                      <p class="reg-date"><span style="width:150px; height:150px;"><strong style="color: #000;">:</strong>No Resume Uploaded</span></p>
                  <%end%>
              </div>
          </div>
      </div>
</div> 

<br>

</section>



<!-- code to preview the uploaded file -->

<!-- <script type="text/javascript">
  $(function() {
  $('#pictureInput').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    var reader = new FileReader();
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      img.src = file.target.result;
      $('#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});
</script> -->


<!-- <form>
  <input type="file" id="pictureInput"> 
</form>
<div id="target">
</div> -->