config/routes.rb
Rails.application.routes.draw do


  get "reports/renewal_report"
  get "reports/dynamic_renewal_data"

  get "agreement_renewals/form"
  post "agreement_renewals/form"

  get "users/franchisee_profile"

  get "due_payslip" => "installment_details#due_royalty_pay_slip"
  post "installment_details/update_franchisee_due_royalty_payment"
  get "due_paydetail" => "installment_details#due_royalty_payment_detail"

  get "installment_details/due_royalty_amount"
  
  post "franchisees/emailcheck"

  get "students/deactivate_student"
  get "students/activate_student"

  get "students/deactivated_student_list"

  get "student_fee_pays/fees_receipt"

  get "franchisee_payslip" => "royalty_details#franchisee_royalty_pay_slip"
  post "royalty_details/update_franchisee_royalty_payment"
  get "franchisee_paydetail" => "royalty_details#franchisee_royalty_payment_detail"

  get "company_payslip" => "company_royalty_details#company_royalty_pay_slip"
  post "company_royalty_details/update_company_royalty_payment"
  get "company_paydetail" => "company_royalty_details#company_royalty_payment_detail"

  post "installment_details/installment_pay"

  get "installment_details/franchisee_payment_detail"

  get "installment_details/franchisee_pay_slip"
  post "installment_details/franchisee_pay_slip"

  get "royalty_details/royalty"
  get "royalty_details/company"
  get "royalty_details/franchisee_royalty"
  get "royalty_details/current_month_royalty"
  get "royalty_details/get_month_year_franchisee_child_royalty"
  get "royalty_details/current_month_company_royalty"
  get "royalty_details/get_month_year_company_royalty"
  get "pay_status" => "royalty_details#pay_status"
  get "our_pay_status" => "royalty_details#our_pay_status"
  get "our_company_pay" => "royalty_details#our_company_pay"
  get "royalty_pay_to_company" => "royalty_details#royalty_pay_to_company"
  get "royalty_details/pay_status_updation"
  get "announcements/announcement_deactive"

  get 'royalty_details/change_status_true'
  get 'royalty_details/change_status_false'

  get "order_requests/invoice_detail"

  get "invoices/invoice_payment_detail"

  get "invoices/invoice_pay_slip"
  post "invoices/invoice_pay_slip"

  get "purchases/item_check"

  get "purchases/payment_detail"

  get "purchases/pay_slip"
  post "purchases/pay_slip"

  #get "purchases/amount_calculation"

  get "employee_attendances/get_month_year_leave"

  get "emp_monthly_salaries/get_month_year_salary"
  post "emp_monthly_salaries/get_month_year_salary"
    
  get "employee_attendances/monthly_leave"

  get "employee_attendances/leave"
  post "employee_attendances/leave"

  get "print_franchisee" => "franchisees#print_franchisee"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#validate_logins'
  get 'logout' => 'sessions#destroy'
  
  get "franchisees/franchisee_agreement"
  post "franchisees/franchisee_agreement"

  get "franchisees/get_type"
  post "franchisees/get_type"

  get "franchisees/dashboard"
  
  get "sessions/forgot_password"
  post "sessions/forgot_password"
  
  get "sessions/forgot_password_link"
  post "sessions/forgot_password_link"

  get  "reset_password" => "sessions#reset_password", :as => "reset_password"
  post "sessions/reset_password"
  
  post "users/update_new_password"

  
  get "franchisees/franchisee_level"
  
  get "student_attendance"=>"students#student_attendance"
  post "student_attendance"=>"students#student_attendance_create"
  get "attendance_destroy"=>"students#attendance_destroy"
  get "franchisee_dashboard" => "franchisees#franchisee_dashboard"

  get "student_reports" => "reports#student_reports"
  get "student_report_show" => "reports#student_report_show"
  get "student_report_generates" => "reports#student_report_generates"

  get "upgrade_level" => "students#level_show"
  get "student_detail_show" => "students#student_details_show"

  get "student_level_update" => "students#student_level_update"

  get "franchisee_tree" => "franchisees#franchisee_tree"

  get "students_report"=> "reports#all_student_report"

  get "reports/monthwise_student_report"
  get "reports/report_xls_generate"
  get "reports/income"
  get "reports/dynamic_income"



  get "expense_category"=>"expenses#expense_category"
  post "expense_category"=>"expenses#expense_category_create"

  
  resources :agreement_renewals
  resources :expenses

  resources :vendors
  
  resources :announcement_fors
  resources :announcements

  resources :company_royalty_details
  resources :royalty_details
  resources :student_fee_pays
  
  resources :student_fee_pays
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests

  resources :franchisee_inventory_stocks
  resources :installment_details

  resources :franchisee_inventory_stocks
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests
  resources :payments
  resources :purchase_items
  resources :purchases
  resources :company_inventory_stocks

  resources :emp_monthly_salaries
  resources :student_details
  resources :students
  resources :franchisee_agreements
  resources :franchisee_contacts
  resources :franchisee_personals
  resources :franchisees
  resources :users
  resources :employee_attendances
  resources :inventory_items
  resources :employee_contacts
  resources :employee_personals
  resources :employee_salaries
  resources :employees
  resources :roles
  resources :batches

  root "franchisees#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   mount SubdivisionSelect::Engine, at: 'subdivisions'
end

app/models/student_detail.rb
class StudentDetail < ApplicationRecord
  belongs_to :student
  has_many :student_fee_pays
 
  validates_format_of :father_email, :mother_email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, :allow_blank => true, :message=> "Invalid"
  validates_presence_of :father_name, :mother_name, :message=> "Required"
 
  validates_length_of :father_contact_no, :mother_contact_no, :minimum => 10, :allow_blank => true, :message=> "Invalid"
  
end

app/controllers/student_details_controller.rb
class StudentDetailsController < ApplicationController
  before_action :set_student_detail, only: [:show, :edit, :update, :destroy]

  # GET /student_details
  # GET /student_details.json
  def index
    @student_details = StudentDetail.all
  end

  # GET /student_details/1
  # GET /student_details/1.json
  def show
  end

  # GET /student_details/new
  def new
    @student_detail = StudentDetail.new
  end

  # GET /student_details/1/edit
  def edit
  end

  # POST /student_details
  # POST /student_details.json
  def create
    @student_detail = StudentDetail.new(student_detail_params)

    respond_to do |format|
      if @student_detail.save
        format.html { redirect_to @student_detail, notice: 'Student detail was successfully created.' }
        format.json { render :show, status: :created, location: @student_detail }
      else
        format.html { render :new }
        format.json { render json: @student_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_details/1
  # PATCH/PUT /student_details/1.json
  def update
    respond_to do |format|
      if @student_detail.update(student_detail_params)
        format.html { redirect_to @student_detail, notice: 'Student detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_detail }
      else
        format.html { render :edit }
        format.json { render json: @student_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_details/1
  # DELETE /student_details/1.json
  def destroy
    @student_detail.destroy
    respond_to do |format|
      format.html { redirect_to student_details_url, notice: 'Student detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_detail
      @student_detail = StudentDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_detail_params
      params.require(:student_detail).permit(:student_id, :father_name, :father_occupation, :father_email, :father_contact_no, :mother_name, :mother_occupation, :mother_email, :mother_contact_no, :known_by, :reason_to_enroll)
    end
end

app/helpers/student_details_helper.rb
module StudentDetailsHelper
end

app/views/student_details/_form.html.erb
<%= form_with(model: student_detail, local: true) do |form| %>
  <% if student_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_detail.errors.count, "error") %> prohibited this student_detail from being saved:</h2>

      <ul>
      <% student_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id, id: :student_detail_student_id %>
  </div>

  <div class="field">
    <%= form.label :father_name %>
    <%= form.text_field :father_name, id: :student_detail_father_name %>
  </div>

  <div class="field">
    <%= form.label :father_occupation %>
    <%= form.text_field :father_occupation, id: :student_detail_father_occupation %>
  </div>

  <div class="field">
    <%= form.label :father_email %>
    <%= form.text_field :father_email, id: :student_detail_father_email %>
  </div>

  <div class="field">
    <%= form.label :father_contact_no %>
    <%= form.text_field :father_contact_no, id: :student_detail_father_contact_no %>
  </div>

  <div class="field">
    <%= form.label :mother_name %>
    <%= form.text_field :mother_name, id: :student_detail_mother_name %>
  </div>

  <div class="field">
    <%= form.label :mother_occupation %>
    <%= form.text_field :mother_occupation, id: :student_detail_mother_occupation %>
  </div>

  <div class="field">
    <%= form.label :mother_email %>
    <%= form.text_field :mother_email, id: :student_detail_mother_email %>
  </div>

  <div class="field">
    <%= form.label :mother_contact_no %>
    <%= form.text_field :mother_contact_no, id: :student_detail_mother_contact_no %>
  </div>

  <div class="field">
    <%= form.label :known_by %>
    <%= form.text_field :known_by, id: :student_detail_known_by %>
  </div>

  <div class="field">
    <%= form.label :reason_to_enroll %>
    <%= form.text_field :reason_to_enroll, id: :student_detail_reason_to_enroll %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_details/edit.html.erb
<h1>Editing Student Detail</h1>

<%= render 'form', student_detail: @student_detail %>

<%= link_to 'Show', @student_detail %> |
<%= link_to 'Back', student_details_path %>

app/views/student_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Details</h1>

<table>
  <thead>
    <tr>
      <!-- <th>Student</th> -->
      <th>Father name</th>
      <th>Father occupation</th>
      <th>Father email</th>
      <th>Father contact no</th>
      <th>Mother name</th>
      <th>Mother occupation</th>
      <th>Mother email</th>
      <th>Mother contact no</th>
      <th>Known by</th>
      <th>Reason to enroll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_details.each do |student_detail| %>
      <tr>
       <!--  <td><%#= student_detail.student %></td> -->
        <td><%= student_detail.father_name %></td>
        <td><%= student_detail.father_occupation %></td>
        <td><%= student_detail.father_email %></td>
        <td><%= student_detail.father_contact_no %></td>
        <td><%= student_detail.mother_name %></td>
        <td><%= student_detail.mother_occupation %></td>
        <td><%= student_detail.mother_email %></td>
        <td><%= student_detail.mother_contact_no %></td>
        <td><%= student_detail.known_by %></td>
        <td><%= student_detail.reason_to_enroll %></td>
        <td><%= link_to 'Show', student_detail %></td>
        <td><%= link_to 'Edit', edit_student_detail_path(student_detail) %></td>
        <td><%= link_to 'Destroy', student_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Detail', new_student_detail_path %>

app/views/student_details/new.html.erb
<h1>New Student Detail</h1>

<%= render 'form', student_detail: @student_detail %>

<%= link_to 'Back', student_details_path %>

app/views/student_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @student_detail.student %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @student_detail.father_name %>
</p>

<p>
  <strong>Father occupation:</strong>
  <%= @student_detail.father_occupation %>
</p>

<p>
  <strong>Father email:</strong>
  <%= @student_detail.father_email %>
</p>

<p>
  <strong>Father contact no:</strong>
  <%= @student_detail.father_contact_no %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @student_detail.mother_name %>
</p>

<p>
  <strong>Mother occupation:</strong>
  <%= @student_detail.mother_occupation %>
</p>

<p>
  <strong>Mother email:</strong>
  <%= @student_detail.mother_email %>
</p>

<p>
  <strong>Mother contact no:</strong>
  <%= @student_detail.mother_contact_no %>
</p>

<p>
  <strong>Known by:</strong>
  <%= @student_detail.known_by %>
</p>

<p>
  <strong>Reason to enroll:</strong>
  <%= @student_detail.reason_to_enroll %>
</p>

<%= link_to 'Edit', edit_student_detail_path(@student_detail) %> |
<%= link_to 'Back', student_details_path %>