config/routes.rb
Rails.application.routes.draw do


  get "reports/renewal_report"
  get "reports/dynamic_renewal_data"

  get "agreement_renewals/form"
  post "agreement_renewals/form"

  get "users/franchisee_profile"

  get "due_payslip" => "installment_details#due_royalty_pay_slip"
  post "installment_details/update_franchisee_due_royalty_payment"
  get "due_paydetail" => "installment_details#due_royalty_payment_detail"

  get "installment_details/due_royalty_amount"
  
  post "franchisees/emailcheck"

  get "students/deactivate_student"
  get "students/activate_student"

  get "students/deactivated_student_list"

  get "student_fee_pays/fees_receipt"

  get "franchisee_payslip" => "royalty_details#franchisee_royalty_pay_slip"
  post "royalty_details/update_franchisee_royalty_payment"
  get "franchisee_paydetail" => "royalty_details#franchisee_royalty_payment_detail"

  get "company_payslip" => "company_royalty_details#company_royalty_pay_slip"
  post "company_royalty_details/update_company_royalty_payment"
  get "company_paydetail" => "company_royalty_details#company_royalty_payment_detail"

  post "installment_details/installment_pay"

  get "installment_details/franchisee_payment_detail"

  get "installment_details/franchisee_pay_slip"
  post "installment_details/franchisee_pay_slip"

  get "royalty_details/royalty"
  get "royalty_details/company"
  get "royalty_details/franchisee_royalty"
  get "royalty_details/current_month_royalty"
  get "royalty_details/get_month_year_franchisee_child_royalty"
  get "royalty_details/current_month_company_royalty"
  get "royalty_details/get_month_year_company_royalty"
  get "pay_status" => "royalty_details#pay_status"
  get "our_pay_status" => "royalty_details#our_pay_status"
  get "our_company_pay" => "royalty_details#our_company_pay"
  get "royalty_pay_to_company" => "royalty_details#royalty_pay_to_company"
  get "royalty_details/pay_status_updation"
  get "announcements/announcement_deactive"

  get 'royalty_details/change_status_true'
  get 'royalty_details/change_status_false'

  get "order_requests/invoice_detail"

  get "invoices/invoice_payment_detail"

  get "invoices/invoice_pay_slip"
  post "invoices/invoice_pay_slip"

  get "purchases/item_check"

  get "purchases/payment_detail"

  get "purchases/pay_slip"
  post "purchases/pay_slip"

  #get "purchases/amount_calculation"

  get "employee_attendances/get_month_year_leave"

  get "emp_monthly_salaries/get_month_year_salary"
  post "emp_monthly_salaries/get_month_year_salary"
    
  get "employee_attendances/monthly_leave"

  get "employee_attendances/leave"
  post "employee_attendances/leave"

  get "print_franchisee" => "franchisees#print_franchisee"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#validate_logins'
  get 'logout' => 'sessions#destroy'
  
  get "franchisees/franchisee_agreement"
  post "franchisees/franchisee_agreement"

  get "franchisees/get_type"
  post "franchisees/get_type"

  get "franchisees/dashboard"
  
  get "sessions/forgot_password"
  post "sessions/forgot_password"
  
  get "sessions/forgot_password_link"
  post "sessions/forgot_password_link"

  get  "reset_password" => "sessions#reset_password", :as => "reset_password"
  post "sessions/reset_password"
  
  post "users/update_new_password"

  
  get "franchisees/franchisee_level"
  
  get "student_attendance"=>"students#student_attendance"
  post "student_attendance"=>"students#student_attendance_create"
  get "attendance_destroy"=>"students#attendance_destroy"
  get "franchisee_dashboard" => "franchisees#franchisee_dashboard"

  get "student_reports" => "reports#student_reports"
  get "student_report_show" => "reports#student_report_show"
  get "student_report_generates" => "reports#student_report_generates"

  get "upgrade_level" => "students#level_show"
  get "student_detail_show" => "students#student_details_show"

  get "student_level_update" => "students#student_level_update"

  get "franchisee_tree" => "franchisees#franchisee_tree"

  get "students_report"=> "reports#all_student_report"

  get "reports/monthwise_student_report"
  get "reports/report_xls_generate"
  get "reports/income"
  get "reports/dynamic_income"



  get "expense_category"=>"expenses#expense_category"
  post "expense_category"=>"expenses#expense_category_create"

  
  resources :agreement_renewals
  resources :expenses

  resources :vendors
  
  resources :announcement_fors
  resources :announcements

  resources :company_royalty_details
  resources :royalty_details
  resources :student_fee_pays
  
  resources :student_fee_pays
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests

  resources :franchisee_inventory_stocks
  resources :installment_details

  resources :franchisee_inventory_stocks
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests
  resources :payments
  resources :purchase_items
  resources :purchases
  resources :company_inventory_stocks

  resources :emp_monthly_salaries
  resources :student_details
  resources :students
  resources :franchisee_agreements
  resources :franchisee_contacts
  resources :franchisee_personals
  resources :franchisees
  resources :users
  resources :employee_attendances
  resources :inventory_items
  resources :employee_contacts
  resources :employee_personals
  resources :employee_salaries
  resources :employees
  resources :roles
  resources :batches

  root "franchisees#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   mount SubdivisionSelect::Engine, at: 'subdivisions'
end

app/models/student_fee_pay.rb
class StudentFeePay < ApplicationRecord

  belongs_to :student_detail
  belongs_to :franchisee

  validates :number_of_classes, :payer_name, :amount, :payment_mode, :fee_type, :dated, presence: { :message => "Required" }

  def self.student_royalty(data)

    royalty = FranchiseeRoyalty.find_by(franchisee_id: data.franchisee_id)
    
    if royalty.present?
  
        if royalty.to_nf.present?
           amount1 = royalty.student_nf_royalty*data.amount/100
            if RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_nf, royalty_type: true).present?
                date1 = RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_nf, royalty_type: true).first.created_at.to_date
                    if (Date.today.at_beginning_of_month..Date.today.at_end_of_month).include?(date1)
                      data1 = RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_nf, royalty_type: true)
                      upamount1 = data1.first.amount+amount1
                      data1.first.update(amount: upamount1)
                   else
                      RoyaltyDetail.create(franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_nf, amount: amount1, royalty_type: true, paid_status: false)
                   end
            else
               RoyaltyDetail.create(franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_nf, amount: amount1, royalty_type: true, paid_status: false)
            end
        end



    if royalty.to_mf.present?
    
       amount2 = royalty.student_mf_royalty*data.amount/100    
      if RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_mf, royalty_type: true).present?
         date2 = RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_mf, royalty_type: true).first.created_at.to_date
            if (Date.today.at_beginning_of_month..Date.today.at_end_of_month).include?(date2)
              data2 = RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_mf, royalty_type: true)
              upamount2 = data2.first.amount+amount2
              data2.first.update(amount: upamount2)
           else
             RoyaltyDetail.create(franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_mf, amount: amount2, royalty_type: true, paid_status: false)
           end
      else
        RoyaltyDetail.create(franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_mf, amount: amount2, royalty_type: true, paid_status: false)
      end
    end



     if royalty.to_df.present?

       amount3 = royalty.student_df_royalty*data.amount/100
      if RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_df, royalty_type: true).present?
         date3 = RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_df, royalty_type: true).first.created_at.to_date
         if (Date.today.at_beginning_of_month..Date.today.at_end_of_month).include?(date3)
        data3 = RoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_df, royalty_type: true)
        upamount3 = data3.first.amount+amount3
         data3.first.update(amount: upamount3)
       else
        RoyaltyDetail.create(franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_df, amount: amount3, royalty_type: true, paid_status: false)
       end
      else
        RoyaltyDetail.create(franchisee_id: royalty.franchisee_id, to_franchisee: royalty.to_df, amount: amount3, royalty_type: true, paid_status: false)
      end

     end

   end

 end
 


  def self.company_royalty(data)

  	royalty = CompanyRoyalty.find_by(franchisee_id: data.franchisee_id)
  	if royalty.present?
       amount5 = royalty.student_royalty*data.amount/100
         if CompanyRoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: data.franchisee_id, royalty_type: true).present?
           data5 = CompanyRoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: data.franchisee_id, royalty_type: true)
            date5 = CompanyRoyaltyDetail.where(created_at: Date.today.at_beginning_of_month..Date.today.at_end_of_month, franchisee_id: data.franchisee_id, royalty_type: true).first.created_at.to_date
              if (Date.today.at_beginning_of_month..Date.today.at_end_of_month).include?(date5)
  		          upamount5 = data5.first.amount+amount5
                data5.first.update(amount: upamount5)
              else
  		          CompanyRoyaltyDetail.create(franchisee_id: royalty.franchisee_id, amount: amount5, royalty_type: true, paid_status: false)
              end
          else
            CompanyRoyaltyDetail.create(franchisee_id: royalty.franchisee_id, amount: amount5, royalty_type: true, paid_status: false)
          end
  	end
  end

  def self.exclude_royalty(data)
    company_royalty = CompanyRoyalty.find_by(franchisee_id: data.franchisee_id)
    franchisee_royalty = FranchiseeRoyalty.find_by(franchisee_id: data.franchisee_id) 
    if franchisee_royalty.present?
  
      aa = franchisee_royalty.to_nf.present? ? franchisee_royalty.student_nf_royalty : 0
      bb = franchisee_royalty.to_mf.present? ? franchisee_royalty.student_mf_royalty : 0
      cc = franchisee_royalty.to_df.present? ? franchisee_royalty.student_df_royalty : 0
      dd = company_royalty.student_royalty
      royalty = aa+bb+cc+dd
      royalty_amount = royalty*data.amount/100
      balance = data.amount - royalty_amount
      return balance
    else
      royalty = company_royalty.student_royalty
      royalty_amount = royalty*data.amount/100
      balance = data.amount - royalty_amount
     return balance
    end
  end
end

app/controllers/student_fee_pays_controller.rb
class StudentFeePaysController < ApplicationController
  before_action :set_student_fee_pay, only: [:edit, :update, :destroy]

  # GET /student_fee_pays
  # GET /student_fee_pays.json
  def index
    @student_fee_pays = StudentFeePay.all
  end

  # GET /student_fee_pays/1
  # GET /student_fee_pays/1.json
  def show

    @student_fee_pay = Student.find(params[:id]).student_detail.student_fee_pays.last
      #byebug
      # respond_to do |format|
      #   format.html
      #   format.pdf do
      #     pdf = render_to_string pdf: "Test", template: "student_fee_pays/_fees_receipt.html.erb", encoding: "UTF-8"
      #     save_path = Rails.root.join('pdfs','test.pdf')
      #     File.open(save_path, 'wb') do |file|
      #       file << pdf
      #     end
      #     system("lpr", "pdfs/test.pdf")
      #   end    
      # end
  end

  # def bill_pdf
  #      @status = params[:act]
  #     @job_card = JobCard.find(params[:id])
  #     respond_to do |format|
  #       format.html
  #       format.pdf do
  #         render :pdf => "JobCard_bill",disposition: "attachment", :template => 'job_cards/_download.html.erb'
  #       end
  #     end
  # end

  # GET /student_fee_pays/new
  def new
    @student_detail = StudentDetail.find(params[:id])
    @student_fee_pay = StudentFeePay.new
    @franchisee = current_user.franchisee    
  end

  # GET /student_fee_pays/1/edit
  def edit
  end

  # POST /student_fee_pays
  # POST /student_fee_pays.json
  def create
    @student_fee_pay = StudentFeePay.new(student_fee_pay_params)

    respond_to do |format|
      if @student_fee_pay.save
        @student_detail = @student_fee_pay.student_detail_id
        #StudentFeeReceiptMailer.send_studentfee_receipt(@student_detail, @student_fee_pay.id).deliver_now!
 
        if params[:student_fee_pay][:fee_type] == "Class Fee"
        StudentFeePay.student_royalty(@student_fee_pay)
        StudentFeePay.company_royalty(@student_fee_pay)
        @balance = StudentFeePay.exclude_royalty(@student_fee_pay)
      
        @student_fee_pay.update(exclude_royalty: @balance)
      end
        format.html { redirect_to students_url, notice: 'Student fee pay was successfully created.' }
        format.json { render :show, status: :created, location: @student_fee_pay }
      else
        format.html { render :new }
        format.json { render json: @student_fee_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_fee_pays/1
  # PATCH/PUT /student_fee_pays/1.json
  def update
    respond_to do |format|
      if @student_fee_pay.update(student_fee_pay_params)
        format.html { redirect_to @student_fee_pay, notice: 'Student fee pay was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_fee_pay }
      else
        format.html { render :edit }
        format.json { render json: @student_fee_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_fee_pays/1
  # DELETE /student_fee_pays/1.json
  def destroy
    @student_fee_pay.destroy
    respond_to do |format|
      format.html { redirect_to student_fee_pays_url, notice: 'Student fee pay was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def fees_receipt
  #   @student = params[:id]
  #   @fee_detail = Student.find(params[:id]).student_detail.student_fee_pays.last.id
  #   #StudentFeeReceiptMailer.fees_receipt(@student, @fee_receipt).deliver_now!
  # end

  def fees_receipt

    @student_fee_pay = StudentFeePay.find(params[:id])
    @student_detail = @student_fee_pay.student_detail_id
      respond_to do |format|
        format.html
        format.pdf do
        render :pdf => "FeesReceipt", disposition: "attachment", :template => 'student_fee_pays/_fees_receipt.html.erb', :save_to_file => Rails.root.join('public/pdfs', "#{@student_fee_pay.student_detail.student.student_name}(#{@student_fee_pay.dated.to_date.strftime("%d-%m-%Y") }).pdf")
      end
    end
    @generated_pdf_name = "#{@student_fee_pay.student_detail.student.student_name}(#{@student_fee_pay.dated.to_date.strftime("%d-%m-%Y") }).pdf"
    StudentFeeReceiptMailer.send_studentfee_receipt(@student_detail, @student_fee_pay.id, @generated_pdf_name).deliver_now!
  end


     #.student_detail.student_fee_pays.last
    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #   pdf = render_to_string pdf: "FeesReceipt", template: "student_fee_pays/_fees_receipt.html.erb", encoding: "UTF-8"
    #   save_path = Rails.root.join('pdfs','fees_receipt.pdf')
    #   File.open(save_path, 'wb') do |file|
    #     file << pdf
    #   end
    #    system("lpr", "pdfs/fees_receipt.pdf")
    #   end    
    # end

     
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_fee_pay
      @student_fee_pay = StudentFeePay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_fee_pay_params
      params.require(:student_fee_pay).permit!#(:amount, :reference_number, :dated, :number_of_classes, :fee_type, :payer_name, :student_detail_id, :franchisee_id)
    end
end

app/helpers/student_fee_pays_helper.rb
module StudentFeePaysHelper

	def fee_type
		
		 if @student_detail.student_fee_pays.where(fee_type: "Registration Fee").count < 1 # => &&  @student_detail.student_fee_pays.where(fee_type: "Class Fee").count < 3
		 ['Registration Fee', 'Class Fee' ] 
		else
		 ['Class Fee']
		end
  	end

  	def payment_mode
  		['Cash', 'Cheque', 'Online' ] 
  		
  	end
end

app/views/student_fee_pays/edit.html.erb
<h1>Editing Student Fee Pay</h1>

<%= render 'form', student_fee_pay: @student_fee_pay %>

<%= link_to 'Show', @student_fee_pay %> |
<%= link_to 'Back', student_fee_pays_path %>

app/views/student_fee_pays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Fee Pays</h1>

<table class ="table">
  <thead>
    <tr>
    <th>Student Name </th>
      <th>Amount</th>
      <th>Reference number</th>
      <th>Dated</th>
     
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @student_fee_pays.each do |student_fee_pay| %>
      <tr>
        <td><%= student_fee_pay.student_detail.student.student_name %>
        <td><%= student_fee_pay.amount %></td>
        <td><%= student_fee_pay.reference_number %></td>
        <td><%= student_fee_pay.dated %></td>
        <td><%= link_to 'Show', student_fee_pay %></td>
        <td><%= link_to 'Edit', edit_student_fee_pay_path(student_fee_pay) %></td>
        <td><%= link_to 'Destroy', student_fee_pay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Fee Pay', new_student_fee_pay_path %>

app/views/student_fee_pays/new.html.erb
<!-- <h1>New Student Fee Pay</h1>


<!%= render 'form', student_fee_pay: @student_fee_pay %>

<!%= link_to 'Back', student_fee_pays_path %>
 -->


<div class="card">
<div class="card-header">
    <h3>Student Fee Payment Form
    <%= link_to "<i class='fa fa-reply'></i>".html_safe, students_path, class: "head-title pull-right" %></h3>
</div>
<div class="card-body"><%= render 'form', student_fee_pay: @student_fee_pay %></div>
</div>

app/views/student_fee_pays/show.html.erb
<!-- <input type="button" class="btn btn-orange" value="Print" onclick="javascript:printDiv('printablediv')" /> 
 -->
 
<%#= link_to "<i class='btn btn-sm btn-blue fa fa-send'></i>".html_safe, student_fee_pays_fees_receipt_path(id: @student_fee_pay.id), title: "Send Fee Receipt" %>
<div class="col-md-2">
 <a class="dropdown-item fa fa-share btn btn-blue" href="<%= student_fee_pays_fees_receipt_path(id: @student_fee_pay.id,format: "pdf") %>"> Send</a>
</div>

<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-md-9">
				<h3><b>BrainCarve Educare India Pvt. Ltd.</b></h3>
				Head Office : 23 / 7, Ganapathy 1st Street, Avvai Nagar, Thiruvanmiyur,<br>
				Chennai - 600041. Tamilnadu, India.<br>
				Mobile : <b>9884400622, 9940036808</b><br>
				E-mail : mail2braincarve@gmail.com | web : www.braincarve.co.in<br>
			</div>

			<div class=" col-md-3 pull-right">
				
				FEE RECEIPT<br>
				No. :<br>
				<p></p>
				Date :  &nbsp;&nbsp;&nbsp;<b class="bill_date"><%= @student_fee_pay.dated.to_date.strftime("%d-%m-%Y") if @student_fee_pay.dated %></b><br>

				ISO 9001 : 2008 Certified Company TM.<br>
			</div>

		</div>

	</div>

	<div class="card-body">

		<div class="row">

			<div class="col-md-3">
				 <div class="logo" style="padding: 40px;"><%= image_tag "logo.png" %></div>
			</div>

			<div class="col-md-9">

				<p style="font-size: 16px; color: grey">

				Received with thanks from Mr/Mrs  &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.payer_name.capitalize %></b><br>
				Mobile  &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.student_detail.student.contact_no if @student_fee_pay.student_detail %></b> &nbsp;&nbsp;&nbsp; Email  &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.student_detail.father_email if @student_fee_pay.student_detail %></b> <br>
				the sum of Rupees (in words)  &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.amount %></b>&nbsp;&nbsp;&nbsp; Only<br>
				being the amount for level &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.level %></b>&nbsp;&nbsp;&nbsp; Regn./month &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.student_detail.student.registration_date.to_date.strftime("%B") if @student_fee_pay.student_detail %></b><br>
				for Student &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.student_detail.student.student_name if @student_fee_pay.student_detail %></b> &nbsp;&nbsp;&nbsp; std &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.student_detail.student.student_class if @student_fee_pay.student_detail %></b> <br>
				by Cash / Cheque / D.D. No. &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.reference_number %></b>  Dated &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= @student_fee_pay.dated.to_date.strftime("%d-%m-%Y") if @student_fee_pay.dated %></b> <br>
				drawn on &nbsp;&nbsp;&nbsp;<b class="fees_content"><%= current_user.franchisee.location %></b>&nbsp;&nbsp;&nbsp; Center Location 

				</p>

			</div>

		</div>

		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6">
				<!-- <div class="pull-right">For BrainCarve Educare India Pvt. Ltd.</div> -->
				<div class="amount-box"><center class="amount-paid"><i class="fa fa-rupee" style="font-size:24px"></i> &nbsp;&nbsp;&nbsp;<%= @student_fee_pay.amount %>&nbsp;&nbsp;&nbsp;</center></div>
			</div>
			<div class="col-md-3">For BrainCarve Educare India Pvt. Ltd.</div>
		</div>

	</div>

	<div class="card-footer">

		Head Office : Dear Parents, Compliment ............. ? Complaints ............. ? Tell us, We value your Feedback

	</div>


</div>


<!-- 
<div id="printablediv" style="width: 100%; background-color: Blue; height: 200px; display: none;">
        <%#= render 'fees_receipt', student_fee_pay: @student_fee_pay %>
    </div>
 -->

<style type="text/css">
.card-header{
	background-color: white!important;
	color: black!important;
}
.amount-box{
	width:225px;
	height:60px;
	border:1px solid grey;
}
.amount-paid{
	margin-top: 13px;
	color: #000;
	font-size: 22px;
}
.fees_content{
	color: #000;
	border-bottom: 1px dotted grey;
    text-decoration: none;
	font-size: 16px;
	font-style: italic;
}
.bill_date{
	color: #000;
	border-bottom: 1px dotted grey;
    text-decoration: none;
	font-style: italic;
}
.btn-blue{
  background-color: #007bff;
  color: #fff;
}
</style>


<!-- 
<script language="javascript" type="text/javascript">
        function printDiv(divID) {
            //Get the HTML of div
            //var html_code = 
            var divElements = document.getElementById(divID).innerHTML;
            //Get the HTML of whole page
            var oldPage = document.body.innerHTML;

            //Reset the page's HTML with div's HTML only
            document.body.innerHTML = 
            //  "<html><head><title></title></head><body>" + 
              divElements;// + "</body>";

            //Print Page
            window.print();

            //Restore orignal HTML
            document.body.innerHTML = oldPage;       
        }
    </script> -->