config/routes.rb
Rails.application.routes.draw do


  get "reports/renewal_report"
  get "reports/dynamic_renewal_data"

  get "agreement_renewals/form"
  post "agreement_renewals/form"

  get "users/franchisee_profile"

  get "due_payslip" => "installment_details#due_royalty_pay_slip"
  post "installment_details/update_franchisee_due_royalty_payment"
  get "due_paydetail" => "installment_details#due_royalty_payment_detail"

  get "installment_details/due_royalty_amount"
  
  post "franchisees/emailcheck"

  get "students/deactivate_student"
  get "students/activate_student"

  get "students/deactivated_student_list"

  get "student_fee_pays/fees_receipt"

  get "franchisee_payslip" => "royalty_details#franchisee_royalty_pay_slip"
  post "royalty_details/update_franchisee_royalty_payment"
  get "franchisee_paydetail" => "royalty_details#franchisee_royalty_payment_detail"

  get "company_payslip" => "company_royalty_details#company_royalty_pay_slip"
  post "company_royalty_details/update_company_royalty_payment"
  get "company_paydetail" => "company_royalty_details#company_royalty_payment_detail"

  post "installment_details/installment_pay"

  get "installment_details/franchisee_payment_detail"

  get "installment_details/franchisee_pay_slip"
  post "installment_details/franchisee_pay_slip"

  get "royalty_details/royalty"
  get "royalty_details/company"
  get "royalty_details/franchisee_royalty"
  get "royalty_details/current_month_royalty"
  get "royalty_details/get_month_year_franchisee_child_royalty"
  get "royalty_details/current_month_company_royalty"
  get "royalty_details/get_month_year_company_royalty"
  get "pay_status" => "royalty_details#pay_status"
  get "our_pay_status" => "royalty_details#our_pay_status"
  get "our_company_pay" => "royalty_details#our_company_pay"
  get "royalty_pay_to_company" => "royalty_details#royalty_pay_to_company"
  get "royalty_details/pay_status_updation"
  get "announcements/announcement_deactive"

  get 'royalty_details/change_status_true'
  get 'royalty_details/change_status_false'

  get "order_requests/invoice_detail"

  get "invoices/invoice_payment_detail"

  get "invoices/invoice_pay_slip"
  post "invoices/invoice_pay_slip"

  get "purchases/item_check"

  get "purchases/payment_detail"

  get "purchases/pay_slip"
  post "purchases/pay_slip"

  #get "purchases/amount_calculation"

  get "employee_attendances/get_month_year_leave"

  get "emp_monthly_salaries/get_month_year_salary"
  post "emp_monthly_salaries/get_month_year_salary"
    
  get "employee_attendances/monthly_leave"

  get "employee_attendances/leave"
  post "employee_attendances/leave"

  get "print_franchisee" => "franchisees#print_franchisee"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#validate_logins'
  get 'logout' => 'sessions#destroy'
  
  get "franchisees/franchisee_agreement"
  post "franchisees/franchisee_agreement"

  get "franchisees/get_type"
  post "franchisees/get_type"

  get "franchisees/dashboard"
  
  get "sessions/forgot_password"
  post "sessions/forgot_password"
  
  get "sessions/forgot_password_link"
  post "sessions/forgot_password_link"

  get  "reset_password" => "sessions#reset_password", :as => "reset_password"
  post "sessions/reset_password"
  
  post "users/update_new_password"

  
  get "franchisees/franchisee_level"
  
  get "student_attendance"=>"students#student_attendance"
  post "student_attendance"=>"students#student_attendance_create"
  get "attendance_destroy"=>"students#attendance_destroy"
  get "franchisee_dashboard" => "franchisees#franchisee_dashboard"

  get "student_reports" => "reports#student_reports"
  get "student_report_show" => "reports#student_report_show"
  get "student_report_generates" => "reports#student_report_generates"

  get "upgrade_level" => "students#level_show"
  get "student_detail_show" => "students#student_details_show"

  get "student_level_update" => "students#student_level_update"

  get "franchisee_tree" => "franchisees#franchisee_tree"

  get "students_report"=> "reports#all_student_report"

  get "reports/monthwise_student_report"
  get "reports/report_xls_generate"
  get "reports/income"
  get "reports/dynamic_income"



  get "expense_category"=>"expenses#expense_category"
  post "expense_category"=>"expenses#expense_category_create"

  
  resources :agreement_renewals
  resources :expenses

  resources :vendors
  
  resources :announcement_fors
  resources :announcements

  resources :company_royalty_details
  resources :royalty_details
  resources :student_fee_pays
  
  resources :student_fee_pays
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests

  resources :franchisee_inventory_stocks
  resources :installment_details

  resources :franchisee_inventory_stocks
  resources :invoice_payments
  resources :invoice_items
  resources :invoices
  resources :order_request_items
  resources :order_requests
  resources :payments
  resources :purchase_items
  resources :purchases
  resources :company_inventory_stocks

  resources :emp_monthly_salaries
  resources :student_details
  resources :students
  resources :franchisee_agreements
  resources :franchisee_contacts
  resources :franchisee_personals
  resources :franchisees
  resources :users
  resources :employee_attendances
  resources :inventory_items
  resources :employee_contacts
  resources :employee_personals
  resources :employee_salaries
  resources :employees
  resources :roles
  resources :batches

  root "franchisees#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   mount SubdivisionSelect::Engine, at: 'subdivisions'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	def student_reports
    @students = Student.where(created_by_id: session[:user_id]).order(created_at: :desc)
	end

	def student_report_show
		
		
    @students_report = Student.find(params[:student_id])
    student_detail = StudentDetail.find(params[:student_id]).id

    @student_fee = StudentFeePay.where(student_detail_id: student_detail)
    @attendance = Attendance.where(student_id: params[:student_id])

	end

	def student_report_generates

		if params[:format] == "xls"
			data= params[:id]
			@students_report = Student.find(params[:id])
			student_detail = StudentDetail.find(params[:id]).id

    @student_fee = StudentFeePay.where(student_detail_id: student_detail)
    @attendance = Attendance.where(student_id: params[:id])
      # @service = params[:data]
        respond_to do |format|
          format.html
          format.xls# { template = 'purchase_logs/pdf_down.html.erb' }
        end
      end
	end	

  def all_student_report
 
    @selected_period = 1.month.ago.beginning_of_month.to_date..1.month.ago.end_of_month.to_date
    #Student.where(created_by_id: session[:user_id]).map{|i| i.student_detail}.map{|j| j.student_fee_pays.where(fee_type: "Class Fee").group_by{|k| [k.dated.month, k.dated.year]}}
    @students = Student.where(created_by_id: session[:user_id]).order(created_at: :desc)
  end

  def monthwise_student_report
    #byebug
    converted_date = Date.new(params[:year_selected].to_i, params[:month_selected].to_i)
    @selected_period = converted_date.to_date.beginning_of_month..converted_date.to_date.end_of_month
    #@student_payments = StudentFeePay.where(franchisee_id: current_user.franchisee.id, dated: selected_period,  fee_type: "Class Fee")
    @students = Student.where(created_by_id: session[:user_id]).order(created_at: :desc)
  end

  def report_xls_generate
    #@selected_period = params[:date].map{|i| i}
    @selected_period = params[:date]
    @students = Student.where(id: params[:data])
  end


  def income
    @payment = Payment.where(payment_date: 1.month.ago.beginning_of_month..1.month.ago.end_of_month)
     @exp = Expense.where(date: 1.month.ago.beginning_of_month..1.month.ago.end_of_month)
     @payments =  @payment.present? ? @payment : []
        @expes =  @exp.present? ? @exp : []
     @expense =  @payments + @expes
       
        @invoice = InvoicePayment.where(payment_date: 1.month.ago.beginning_of_month..1.month.ago.end_of_month)
      @royalty = CompanyRoyaltyDetail.where(created_at: 1.month.ago.beginning_of_month..1.month.ago.end_of_month) 
    
    @invoice_amount =  @invoice.present? ? @invoice : []
      @royalty_amount =  @royalty.present? ? @royalty : []

     @income = @invoice_amount + @royalty_amount

  end

  def dynamic_income
   if params[:date_range].present?
    date_range = params[:date_range]
    if date_range.split('to').length > 1

      startDate = params[:date_range].split('to')[0].strip.to_date-1 if params[:date_range].present?   
      endDate = params[:date_range].split('to')[1].strip.to_date+1 if params[:date_range].present?

   #byebug
      @payment = Payment.where(payment_date: startDate..endDate) if Payment.where(payment_date: startDate..endDate).present?
      @exp = Expense.where(date: startDate..endDate) if Expense.where(date: startDate..endDate).present?
      
    @payments =  @payment.present? ? @payment : []
        @expes =  @exp.present? ? @exp : []
     @expense =  @payments + @expes
     
      @invoice = InvoicePayment.where(payment_date: startDate..endDate)
      @royalty = CompanyRoyaltyDetail.where(created_at: startDate..endDate) 

      @invoice_amount =  @invoice.present? ? @invoice : []
      @royalty_amount =  @royalty.present? ? @royalty : []

     @income = @invoice_amount + @royalty_amount
       
    end
 
  else
     @payment = Payment.where(payment_date: 1.month.ago.beginning_of_month..1.month.ago.end_of_month)
     @exp = Expense.where(date: 1.month.ago.beginning_of_month..1.month.ago.end_of_month)
     @payments =  @payment.present? ? @payment : []
        @expes =  @exp.present? ? @exp : []
     @expense =  @payments + @expes
       
        @invoice = InvoicePayment.where(payment_date: 1.month.ago.beginning_of_month..1.month.ago.end_of_month)
      @royalty = CompanyRoyaltyDetail.where(created_at: 1.month.ago.beginning_of_month..1.month.ago.end_of_month) 
    
    @invoice_amount =  @invoice.present? ? @invoice : []
      @royalty_amount =  @royalty.present? ? @royalty : []

     @income = @invoice_amount + @royalty_amount


  end
  end


  def renewal_report
    @renewals = Franchisee.all
  end

  def dynamic_renewal_data
      if params[:date_range].present?
          date_range = params[:date_range]
              if date_range.split('to').length > 1
                startDate = params[:date_range].split('to')[0].strip.to_date-1 if params[:date_range].present?   
                endDate = params[:date_range].split('to')[1].strip.to_date+1 if params[:date_range].present?

                @renewals = Franchisee.where(latest_renewal: startDate..endDate)
              else
                @renewals = Franchisee.all
              end
        else
           @renewals = Franchisee.all
        end      
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_dynamic_income.html.erb
<ul class="nav nav-tabs active_tab_color" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" href="#profile" role="tab" data-toggle="tab"><h6 style="font-style: italic;">Income</h6></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#two" role="tab" data-toggle="tab"><h6 style="font-style: italic;">Expense</h6></a>
  </li>
</ul>

<div class="tab-content">
 <div role="tabpanel" class="tab-pane fade show in active" id="profile">
    <table id="to_company_bc_company_table_income" class="table table-striped display" cellspacing="0" width="100%">
  <thead>
    <tr>
     <th>Date</th>
      <th>Royalty / Inventry</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>

   <% @income.each do |income| %>
      <tr>

       
<!--         ii.is_a?(CompanyRoyaltyDetail)
 -->       
  
   
        <%if income.is_a?(CompanyRoyaltyDetail)%>
        <td><%= income.created_at.strftime("%d-%m-%Y")%></td>
        <td> Royalty </td>
        <td><%= income.amount%></td>
        <%else%>
        <td><%= income.payment_date.strftime("%d-%m-%Y")%></td>
        <td> Inventry </td>
        <td><%= income.amount_paid%></td>

        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

 <div role="tabpanel" class="tab-pane fade" id="two">
            
               <%= render partial: "reports/expense_amount" %>
      </div>
</div>
 
 


<script type="text/javascript">
$(document).ready(function() {
  $("#to_company_bc_company_table_income").dataTable({
    columnDefs: [
    {orderable: false, targets: -1},
    {orderable: false, targets: -2},
    {orderable: false, targets: -3},
    ]
  });
});
</script>

<style type="text/css">
.btn-orange{
color: #fff;
}
.crud{
    color: green;
  }
  .actn{
/*display: none;*/
width: 58px;
/*position: fixed;*/
background-color: #e26616;
right: 0px;
/*top: 303px;*/
z-index: 10;
border-radius: 8px;
height: 104px;
padding: 12px 5px;
}
</style>


<!-- actions bar -->


<script>
/*$(document).ready(function(){
   $( "#actions").hide();
    $(".show").click(function(){
        $("#actions").show();
    });
   
});*/
</script> 



<script type="text/javascript">
  $(document).ready(function() {
var table = $('#franchisee_table').DataTable({
   "scrollY":  '50vh',
    "crollCollapse": true,
    "scrollX": true
});
   
</script>

<style type="text/css">
  .side-pop{ 
    height:auto; 
    padding:2px; 
    background-color:#E67A3F;
    border:1px solid #E67A3F; 
    position:fixed; 
    top:50%; 
    right:0; 
    -webkit-transition: all 0.5s ease;
    transition:all 0.5s ease; 
    border-radius:4px 0 0 4px; 
    margin-top:-100px;
  }
.side-pop ul{ 
  width:auto; 
  height:auto; 
  margin:0; 
  padding:0; 
}
.side-pop ul li{ 
  float:none; 
  width:30px; 
  height:20px; 
  margin:0; padding:0; 
  list-style:none; 
  text-align:center; 
  margin-bottom:10px; 
  font-size:20px; 
}
.side-pop ul li a{ 
  color:#fff; 
  display:block; 
  text-decoration:none; 
  text-align:center;
  -webkit-transition: all 0.2s ease;
    -moz-transition: all 0.2s ease; 
    -ms-transition: all 0.2s ease; 
    -o-transition: all 0.2s ease; 
    transition: all 0.2s ease; 
  }
.side-pop ul li a strong{
  font-weight:900;
}  
.side-pop ul li a:hover{ 
  color:#f0ebf0;
  -webkit-transform:scale(1.25); 
    -moz-transform:scale(1.25); 
    -ms-transform:scale(1.25); 
    -o-transform:scale(1.25);
     transform:scale(1.25);}
.side-show{
  right:0px;
}
.side-pop .close{ 
  width:auto; 
  font-size:15px; 
  color:#BE2134; 
  margin-top:5px; 
  text-align:center;
}
</style>

app/views/reports/_monthwise_student_report.html.erb
	
			
	<%#= link_to "Excel", reports_report_xls_generate_path(format: "xls", data: @students.ids, date: @selected_period.map{|i| i}) %>
	 
		<table id="dynamic_student_report" class="table table-striped display" cellspacing="0" width="100%">
		 <thead>
		   <tr>
		    <th>Name</th>
		    <th>Grade</th>
		    <th>Level Joind</th>
		    <th>Current Level</th>
		    <th>Parent Name</th>
		    <th>Contact</th>
		    <th>Date of Join</th>
		    <th>Class Fee</th>
		    <th>Royalty</th>
		    <th>Center</th>
		    
		 
		    
		   </tr>
		 </thead>
		 <tbody>
		<% @students.each do |student| %>
		      <tr>
		
			      <td class="std-name"><%= student.student_name %></td> 
			      
			      <td class="std-name"><%= student.student_class %></td> 

			      <td><%= student.level_join %></td>

			      <td class="sch-name"><%= student.level %></td> 

                 <td class="sch-name"><%= student.student_detail.father_name %></td> 
			      
			      <td class="sch-name"><%= student.contact_no %></td>
			      
			      <td class="reg-date"><%= student.registration_date.to_date.strftime("%d-%m-%Y") if student.registration_date%></td>

        
			      <td><%= student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:amount).sum%></td>
			     
			     <td><%= student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:amount).sum - student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:exclude_royalty).sum%></td>

			     <td> <%= student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:exclude_royalty).sum%></td>

			     
			     </tr>
			    <% end %>
		   
		  </tbody>
		</table>

<script type="text/javascript">
    
//     $('.customer_select').change(function(){
//   var id = $(this).val();
//   $.get( "/student_report_show?student_id="+id );
  
// });

   
// $('.select').selectize({
// 	sortField: 'text'
// 	});


  $(document).ready(function() {
  $("#dynamic_student_report").dataTable();
});
</script>

app/views/reports/all_student_report.html.erb
<div class="card">
	<div class="card-header">
	 <h3>Overall Students Report

	 	<div class="pull-right">
				<%= link_to "<i class='btn btn-default fa fa-download'></i>".html_safe, reports_report_xls_generate_path(format: "xls", data: @students.ids, date: @selected_period.map{|i| i}), title: "Downoad Report" %>
			</div>

    <div class="col-md-2 pull-right"">
        <%= select_tag "year_to_select", options_from_collection_for_select(year_list, :to_s, :to_s, selected: Date.current.year), { class: "form-control", id: 'year_to_select'} %>
      </div>
    <div class="col-md-2 pull-right"> 
        <%= select_tag "month_to_select", options_from_collection_for_select(month_list, :first, :last), { class: "form-control", id: 'month_to_select'} %>
      </div>
    </h3>
	</div>
	<div class="card-body">
		<div class="card-title">
			
	 <div id="dynamic_report_data">

		<table id="student_report" class="table table-striped display" cellspacing="0" width="100%">
		 <thead>
		   <tr>
		    <th>Name</th>
		    <th>Grade</th>
		    <th>Level Joind</th>
		    <th>Current Level</th>
		    <th>Parent Name</th>
		    <th>Contact</th>
		    <th>Date of Join</th>
		    <th>Class Fee</th>
		    <th>Royalty</th>
		    <th>Center</th>
		    
		 
		    
		   </tr>
		 </thead>
		 <tbody>
		<% @students.each do |student| %>
		      <tr>
		
			      <td class="std-name"><%= student.student_name %></td> 
			      
			      <td class="std-name"><%= student.student_class %></td> 

			      <td><%= student.level_join %></td>

			      <td class="sch-name"><%= student.level %></td> 

                 <td class="sch-name"><%= student.student_detail.father_name %></td> 
			      
			      <td class="sch-name"><%= student.contact_no %></td>
			      
			      <td class="reg-date"><%= student.registration_date.to_date.strftime("%d-%m-%Y") if student.registration_date%></td>

        
			      <td><%= student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:amount).sum%></td>
			     
			     <td><%= student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:amount).sum - student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:exclude_royalty).sum%></td>

			     <td> <%= student.student_detail.student_fee_pays.where(dated: @selected_period, fee_type: "Class Fee").pluck(:exclude_royalty).sum%></td>

			     
			     </tr>
			    <% end %>
		   
		  </tbody>
		</table>
	</div>

</div>
</div>
</div>

	<script type="text/javascript">
    
//     $('.customer_select').change(function(){
//   var id = $(this).val();
//   $.get( "/student_report_show?student_id="+id );
  
// });

   
// $('.select').selectize({
// 	sortField: 'text'
// 	});


  $(document).ready(function() {
  $("#student_report").dataTable();
});
</script>
<script type="text/javascript">
	$('#month_to_select').on('change', function () {
  var month_input =($(this).val());
  var year_input = ($("#year_to_select").val());
      $.ajax({
        type: "GET",
         url: "/reports/monthwise_student_report?month_selected="+ month_input+"&&year_selected="+year_input,
      })
  });
$('#year_to_select').on('change', function () {
  var month_input = ($("#month_to_select").val());
  var year_input = ($(this).val());
      $.ajax({
        type: "GET",
         url: "/reports/monthwise_student_report?month_selected="+ month_input+"&&year_selected="+year_input,
      })
  });
</script>

app/views/reports/dynamic_income.js.erb
$("#data").html("<%= escape_javascript(render 'reports/dynamic_income') %>")

app/views/reports/dynamic_renewal_data.js.erb
$("#dynamic_renewal_data").html("<%= escape_javascript(render 'reports/dynamic_renewal_data') %>")

app/views/reports/monthwise_student_report.js.erb
$("#dynamic_report_data").html("<%= escape_javascript(render 'reports/monthwise_student_report') %>")

app/views/reports/student_report_show.html.erb
<div class="card" id ="table-scroll">
	<div class="card-header">

		<h3> Student Details
			<div class="pull-right">
			  <%= link_to "<i class='fa fa-download'></i>".html_safe, student_report_generates_path(id: params[:student_id], format: "xls" ) %>
			</div>
			<div class=" col-md-2 pull-right">
			  <%= link_to "<i class='fa fa-reply'></i>".html_safe, student_reports_path, class: " head-title pull-right", data: { confirm: 'Do you want to go to previous page?' } %>
			</div>
		</h3>
	</div>
	<table id="student_repot" class="table table-striped display" cellspacing="0" width="100%">
	 <thead>
	   <tr>
		    <th>Name</th>
		    <th> Joining Date </th>
		    <th>Age</th>
		    <th>Contact Number</th>
		    <th> Level</th>
	    </tr>
	  </thead>
		<tbody>
		
      <tr>
	      <td class="std-name"><%= @students_report.student_name %></td> 
	      <td class="reg-date"><%= @students_report.registration_date.to_date.strftime("%d-%m-%Y") if @students_report.registration_date%></td>      
	      <td class="std-class"><%= @students_report.age %></td>      
	      <td class="cont-no"><%= @students_report.contact_no %></td>
	      <td class="sch-name"><%= @students_report.level %></td> 
	       </td> 
	    </tr>
		   
		  </tbody>
		</table>


	<h5> Student Payments</h5>
		<table class="table table-striped display" cellspacing="0" width="100%">
		 <thead>
		   <tr>
		   <th> Sl.No </th>
		    <th>Payer Name</th>
		    <th> Amount </th>
            <th>Level </th>
		    <th>Reference Number</th>
		    <th>Fee Type</th>
		    <th> Date</th>
		    
		   </tr>
		 </thead>
		 <tbody>
		  <% b = 0 %>
		    <% @student_fee.each do |student| %>
		      <tr>
		          <td class="std-name"><%= b += 1 %></td> 
			      <td class="std-name"><%= student.payer_name %></td> 
			      <td class="reg-date"><%= student.amount%></td> 
			      <td class="cont-no"><%= student.level %></td>     
			      <td class="std-class"><%= student.reference_number %></td>      
			      <td class="cont-no"><%= student.fee_type %></td>
			      <td class="sch-name"><%= student.dated.to_date.strftime("%d-%m-%Y") %></td> 
			       </td> 
			    </tr>
		    <% end %>
		  </tbody>
		</table>
	
<h5> Student Attendance</h5>
		<table class="table table-striped display" cellspacing="0" width="100%">
		 <thead>
		   <tr>
		    
		    <th> Sl.No </th>
		    <th> Level </th>
		    <th>Payment Mode</th>
		   
		    
		   </tr>
		 </thead>
		 <tbody>
		 <% s = 0 %>
		    <% @attendance.each do |student| %>
		    
		      <tr>
			      <td class="std-name"><%= s += 1 %></td> 
			      <td class="std-name"><%= student.level %></td>
			      <td class ="sch-name"><%= student.date.to_date.strftime("%d-%m-%Y") %></td> 
			       </td> 
			    </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>






</div>
</div>

</div>




 <script type="text/javascript">
$(document).ready(function() {

 $("#student_report").dataTable({
   // columnDefs: [
   // {orderable: false, targets: -1},
   // {orderable: false, targets: -2},
   // {orderable: false, targets: -3},
   // ]
 });

});
</script>

<style>
#table-scroll {
  height:800px;
  overflow:auto;  
  margin-top:20px;
}
</style>

app/views/reports/student_reports.html.erb
<div class="card">
	<div class="card-header">
	  Students Report
	</div>
	<div class="card-body">
		<div class="card-title">
			
	
	 
		<table id="student_report" class="table table-striped display" cellspacing="0" width="100%">
		 <thead>
		   <tr>
		    <th>Name</th>
		    <th>Joining Date </th>
		    <th>Age</th>
		    <th>Contact Number</th>
		    <th> Level</th>
		    <th> Action </th>
		    
		   </tr>
		 </thead>
		 <tbody>
		<% @students.each do |student| %>
		      <tr>
			      <td class="std-name"><%= student.student_name %></td> 
			      <td class="reg-date"><%= student.registration_date.to_date.strftime("%d-%m-%Y") if student.registration_date%></td>      
			      <td class="std-class"><%= student.age %></td>      
			      <td class="cont-no"><%= student.contact_no %></td>
			      <td class="sch-name"><%= student.level %></td> 
			      <td><%= link_to "<i class='fa fa-eye btn btn-sm btn-orange' title='View Student'></i>".html_safe, student_report_show_path(student_id: student.id) %></td> 
			     </tr>
			    <% end %>
		   
		  </tbody>
		</table>

</div>
</div>
</div>

	<script type="text/javascript">
    
//     $('.customer_select').change(function(){
//   var id = $(this).val();
//   $.get( "/student_report_show?student_id="+id );
  
// });

   
// $('.select').selectize({
// 	sortField: 'text'
// 	});


  $(document).ready(function() {
  $("#student_report").dataTable();
});
</script>